### ISSUE TITLE
Implement dataset merging at count matrix level

### ISSUE THREAD

**Issue by dakota-hawkins** [BradhamLab/scPipe#14]
Merge count matrices from multiple alignment runs into a single count matrix

- [x] Run on provided flag
- [x] Merge count matrices
- [x] Merge metadata
- [x] Ensure unique sample ids after merging

**Comment by HawkinsDakota** [comment]
Should be conditional given flag in config file

**Comment by HawkinsDakota** [comment]
Should be done before count matrix filtering

**Comment by HawkinsDakota** [comment]
Also merge new metadata files at the same time
