### ISSUE TITLE
Nest tool parameters in config file

### ISSUE THREAD

**Issue by dakota-hawkins** [BradhamLab/scPipe#17]
Nest parameters for each tool within a single parent parameter entry.

Example

params:
    &nbsp;&nbsp;&nbsp;&nbsp;star_genome: {params}
    &nbsp;&nbsp;&nbsp;&nbsp;star_align: {params}
    &nbsp;&nbsp;&nbsp;&nbsp;...

**Comment by HawkinsDakota** [comment]
Actually, just nest every "related" field (e.g. directories, regex patterns, etc.)
